[2022-05-23 20:15:57,207] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-02-12T00:00:00+00:00 [queued]>
[2022-05-23 20:15:57,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2022-02-12T00:00:00+00:00 [queued]>
[2022-05-23 20:15:57,291] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:15:57,292] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-05-23 20:15:57,292] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:15:57,342] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2022-02-12 00:00:00+00:00
[2022-05-23 20:15:57,353] {standard_task_runner.py:52} INFO - Started process 2550 to run task
[2022-05-23 20:15:57,384] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2022-02-12T00:00:00+00:00', '--job-id', '598', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_r1tp8gu', '--error-file', '/tmp/tmp1tql4y28']
[2022-05-23 20:15:57,413] {standard_task_runner.py:80} INFO - Job 598: Subtask second_task
[2022-05-23 20:15:57,544] {task_command.py:369} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2022-02-12T00:00:00+00:00 [running]> on host 061a475e6c14
[2022-05-23 20:15:57,831] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gerson
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-12T00:00:00+00:00
[2022-05-23 20:15:57,836] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-23 20:15:57,837] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-05-23 20:15:57,853] {subprocess.py:85} INFO - Output:
[2022-05-23 20:15:57,856] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-05-23 20:15:57,857] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-23 20:15:57,945] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20220212T000000, start_date=20220523T201557, end_date=20220523T201557
[2022-05-23 20:15:57,990] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-23 20:15:58,048] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
