[2022-05-23 20:14:39,172] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-29T00:00:00+00:00 [queued]>
[2022-05-23 20:14:39,196] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-29T00:00:00+00:00 [queued]>
[2022-05-23 20:14:39,197] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:14:39,197] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-05-23 20:14:39,197] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 20:14:39,225] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): second_task> on 2021-08-29 00:00:00+00:00
[2022-05-23 20:14:39,231] {standard_task_runner.py:52} INFO - Started process 979 to run task
[2022-05-23 20:14:39,243] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-29T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpmh1fol_i', '--error-file', '/tmp/tmpcaynqwro']
[2022-05-23 20:14:39,244] {standard_task_runner.py:80} INFO - Job 98: Subtask second_task
[2022-05-23 20:14:39,358] {task_command.py:369} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-29T00:00:00+00:00 [running]> on host 061a475e6c14
[2022-05-23 20:14:39,473] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gerson
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=second_task
AIRFLOW_CTX_EXECUTION_DATE=2021-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-29T00:00:00+00:00
[2022-05-23 20:14:39,474] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-23 20:14:39,475] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2022-05-23 20:14:39,488] {subprocess.py:85} INFO - Output:
[2022-05-23 20:14:39,490] {subprocess.py:92} INFO - hey, I am task2 and will be running after task1!
[2022-05-23 20:14:39,490] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-23 20:14:39,525] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210829T000000, start_date=20220523T201439, end_date=20220523T201439
[2022-05-23 20:14:39,576] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-23 20:14:39,602] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
